services:
  - type: web
    name: toolxw-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot_render:app --workers 1 --threads 4 --timeout 120
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "8801844480"
      - key: SERVER_SECRET
        sync: false
      - key: DB_PATH
        value: "data/toolxw_files.db"
